### ISSUE TITLE
What do do for rank-deficient matrices 

### ISSUE THREAD

**Issue by bmwilly** [gmgeorg/ForeCA#1]
Hi, thanks for the cool package. 

Is there a recommended way for dealing with rank-deficient matrices before passing to `foreca`? Right now, I get an error 

```
> mod <- foreca(df, n.comp = 10, spectrum.control = sc, entropy.control = ec)
Error in sqrt_matrix(cov(data), return.sqrt.only = FALSE, symmetric = TRUE) : 
  Exact inverse matrix can only be computed for full rank matrices.
In addition: Warning message:
In sqrt_matrix(cov(data), return.sqrt.only = FALSE, symmetric = TRUE) :
  The matrix does not have full rank (= 765):116 eigenvalue(s) equal 0.
```

E.g., is there a way to manually "whiten" the data using the pseudoinverse?

**Comment by gmgeorg** [comment]
I have 2 suggestions:

1. add iid noise to all your time series with variance sigma_eps^2 << min(variance(data)), effectively pushing cov(data) away from 0 by a diagonal matrix with sigma_eps^2.

2. Run PCA (or SFA) first and only select the first 765 - 116 = 649 components, the rest should be all zero eigen-values.  Then run ForeCA on those 649 components, and obtain the `$scores`.

Having said that, while in principle you can run ForeCA on 649 time series, in practice I suggest to reduce this first to << 100 series (or even << 50).  Estimating high-dimensional power spectra for 649 is very time consuming/memory intensive; and it has to be done iteratively for every component over and over again.

Practically my suggestion is

- run PCA (`princomp()`) to get out the 649 non-zero eigenvalue components; 
- run SFA (`sfa()`) and pick the, say, top 30 and bottom 20 components; 
- run ForeCA (`foreca()`) on the pool of 30 + 20 slow features to extract forecastable components.

Both PCA and SFA can be computed quickly / analytically based on a K x K matrix and its eigenvalues; ForeCA requires an iterative solutions on K x K x T power spectra.

btw, do you mind sharing in what context you are using this for?

**Comment by bmwilly** [comment]
Great suggestions, thank you! I especially like the idea of combining PCA/SFA/ForeCA to deal with the time complexity. 

>btw, do you mind sharing in what context you are using this for?

It's really just exploratory at this point, but happy to discuss more. I sent an email to the address on your website. Thanks again.
